In [1]:
from layerd_neat import *

In [2]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Load the Iris dataset
iris = load_iris()
X = iris.data  # Features (4 inputs: sepal length, sepal width, petal length, petal width)
y = iris.target.reshape(-1, 1)  # Target (3 classes: 0, 1, 2)

# Convert the target labels to one-hot encoded format
encoder = OneHotEncoder(sparse_output=False)  # Ensure the output is dense
y_encoded = encoder.fit_transform(y)

# Display the first few entries of the dataset
print("Inputs (first 5):")
print(X[:5])
print("Outputs (first 5):")
print(y_encoded[:5])

# Convert to the format you've been using (list of lists)
inputs = X.tolist()
outputs = y_encoded.tolist()

# Example of how the inputs and outputs would look like
print("Example formatted input:")
print(inputs[:5])
print("Example formatted output:")
print(outputs[:5])


Inputs (first 5):
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Outputs (first 5):
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
Example formatted input:
[[5.1, 3.5, 1.4, 0.2], [4.9, 3.0, 1.4, 0.2], [4.7, 3.2, 1.3, 0.2], [4.6, 3.1, 1.5, 0.2], [5.0, 3.6, 1.4, 0.2]]
Example formatted output:
[[1.0, 0.0, 0.0], [1.0, 0.0, 0.0], [1.0, 0.0, 0.0], [1.0, 0.0, 0.0], [1.0, 0.0, 0.0]]


In [3]:
def run_generation(neat, inputs, outputs):
    evaluations = neat.evaluate_population(inputs, outputs, 100, 0.01)
    participants_id, remaining_id = neat.select_participants(evaluations)

    best = None
    best_id = participants_id[0][0]
    best_score = participants_id[0][1]
    best_losses = participants_id[0][2]

    for p in neat.population:
        if p.id == best_id:
            best = [p, best_score, best_losses]
            break

    print("Best of generation: ", best_id, best_score)
    plot_dag(best[0])

    neat.population = neat.evolve(participants_id, remaining_id)
    """ for dag in neat.population:
        print('-'*150)
        print("id", dag.id)
        plot_dag(dag)
        print(dag) """

In [4]:
#run_generation(neat, inputs, outputs)

In [5]:
neat = NEAT(len(inputs[0]), len(outputs[0]), population_size=4, with_fully_connect=True, error_function=MSE(), output_activation=Sigmoid())

In [6]:
best_of_generations = neat.run(inputs, outputs, epochs=100, generations=20)

100%|██████████| 4/4 [00:00<00:00, 4006.02it/s]


------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 1/20


evaluating DAG's: 100%|██████████| 4/4 [00:00<00:00,  5.72it/s]


Best of generation:  3 Best Score: 0.023858706527859583
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 2/20


evaluating DAG's: 100%|██████████| 4/4 [00:00<00:00,  5.68it/s]


Best of generation:  3 Best Score: 0.7445307355612328
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 3/20


evaluating DAG's: 100%|██████████| 4/4 [00:00<00:00,  5.27it/s]


Best of generation:  0-2-1 Best Score: 0.031315890637785976
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 4/20


evaluating DAG's: 100%|██████████| 4/4 [00:00<00:00,  5.20it/s]


Best of generation:  3-2 Best Score: 0.03341108207304094
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 5/20


evaluating DAG's: 100%|██████████| 4/4 [00:00<00:00,  5.02it/s]


Best of generation:  3-2 Best Score: 0.03319334675162056
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 6/20


evaluating DAG's: 100%|██████████| 4/4 [00:00<00:00,  4.88it/s]


Best of generation:  3-0-0-1 Best Score: 0.021980259471310257
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 7/20


evaluating DAG's: 100%|██████████| 4/4 [00:00<00:00,  4.38it/s]


Best of generation:  3-0-0-2-2 Best Score: 0.7381362353281613
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 8/20


evaluating DAG's: 100%|██████████| 4/4 [00:00<00:00,  4.24it/s]


Best of generation:  3-0-0-2-0-0 Best Score: 0.7422056891962203
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 9/20


evaluating DAG's: 100%|██████████| 4/4 [00:00<00:00,  4.14it/s]


Best of generation:  3-0-0-2-0-2-2 Best Score: 0.7424917462588744
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 10/20


evaluating DAG's: 100%|██████████| 4/4 [00:01<00:00,  3.81it/s]


Best of generation:  3-0-0-2-0-2-0-0 Best Score: 0.7343059381527158
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 11/20


evaluating DAG's: 100%|██████████| 4/4 [00:01<00:00,  3.96it/s]


Best of generation:  3-0-0-2-0-2-0-0 Best Score: 1.0920620846076399
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 12/20


evaluating DAG's: 100%|██████████| 4/4 [00:01<00:00,  3.86it/s]


Best of generation:  3-0-0-2-0-2-2-1-0 Best Score: 0.7423276897376301
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 13/20


evaluating DAG's: 100%|██████████| 4/4 [00:01<00:00,  3.94it/s]


Best of generation:  3-0-0-2-0-2-2-1-0 Best Score: 1.7422383515424398
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 14/20


evaluating DAG's: 100%|██████████| 4/4 [00:01<00:00,  3.84it/s]


Best of generation:  3-0-0-2-0-2-2-1-0 Best Score: 1.7422383515424398
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 15/20


evaluating DAG's: 100%|██████████| 4/4 [00:01<00:00,  2.85it/s]


Best of generation:  3-0-0-2-0-2-2-1-0 Best Score: 1.7422383515424398
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 16/20


evaluating DAG's: 100%|██████████| 4/4 [00:01<00:00,  3.37it/s]


Best of generation:  3-0-0-2-0-2-2-1-0 Best Score: 1.7422383515424398
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 17/20


evaluating DAG's: 100%|██████████| 4/4 [00:01<00:00,  3.36it/s]


Best of generation:  3-0-0-2-0-2-2-1-1-2-2-0-2-0 Best Score: 0.7909206320429768
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 18/20


evaluating DAG's: 100%|██████████| 4/4 [00:01<00:00,  3.55it/s]


Best of generation:  3-0-0-2-0-2-2-1-0-1 Best Score: 1.0539314014847572
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 19/20


evaluating DAG's: 100%|██████████| 4/4 [00:01<00:00,  3.21it/s]


Best of generation:  3-0-0-2-0-2-2-1-0-1 Best Score: 1.0532249315542446
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 20/20


evaluating DAG's: 100%|██████████| 4/4 [00:01<00:00,  3.12it/s]

Best of generation:  3-0-0-2-0-2-2-1-1-2-2-0-2-0-2-2 Best Score: 0.8128488757743422


In [7]:
""" for dag in neat.population:
    print('-'*150)
    print("id", dag.id)
    plot_dag(dag)
    print(dag) """

' for dag in neat.population:\n    print(\'-\'*150)\n    print("id", dag.id)\n    plot_dag(dag)\n    print(dag) '

In [8]:
target_dag : DAG = best_of_generations[-1][0]

plot_dag(target_dag)

print('Has circles:', target_dag.check_for_circular())

Has circles: True


In [9]:
for i in np.random.randint(0, len(inputs), 20):
    res = target_dag.process([inputs[i]])
    print(f"Output: {np.argmax(res)} | Expected: {np.argmax(outputs[i])}")

Output: 0 | Expected: 0
Output: 0 | Expected: 0
Output: 0 | Expected: 0
Output: 2 | Expected: 1
Output: 2 | Expected: 1
Output: 0 | Expected: 0
Output: 0 | Expected: 0
Output: 2 | Expected: 1
Output: 2 | Expected: 2
Output: 2 | Expected: 2
Output: 2 | Expected: 2
Output: 2 | Expected: 1
Output: 0 | Expected: 0
Output: 2 | Expected: 2
Output: 2 | Expected: 1
Output: 2 | Expected: 2
Output: 0 | Expected: 0
Output: 0 | Expected: 0
Output: 2 | Expected: 1
Output: 0 | Expected: 0
