In [2]:
from layerd_neat import *

In [3]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Load the Iris dataset
iris = load_iris()
X = iris.data  # Features (4 inputs: sepal length, sepal width, petal length, petal width)
y = iris.target.reshape(-1, 1)  # Target (3 classes: 0, 1, 2)

# Convert the target labels to one-hot encoded format
encoder = OneHotEncoder(sparse_output=False)  # Ensure the output is dense
y_encoded = encoder.fit_transform(y)

# Display the first few entries of the dataset
print("Inputs (first 5):")
print(X[:5])
print("Outputs (first 5):")
print(y_encoded[:5])

# Convert to the format you've been using (list of lists)
inputs = X.tolist()
outputs = y_encoded.tolist()

# Example of how the inputs and outputs would look like
print("Example formatted input:")
print(inputs[:5])
print("Example formatted output:")
print(outputs[:5])


Inputs (first 5):
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Outputs (first 5):
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
Example formatted input:
[[5.1, 3.5, 1.4, 0.2], [4.9, 3.0, 1.4, 0.2], [4.7, 3.2, 1.3, 0.2], [4.6, 3.1, 1.5, 0.2], [5.0, 3.6, 1.4, 0.2]]
Example formatted output:
[[1.0, 0.0, 0.0], [1.0, 0.0, 0.0], [1.0, 0.0, 0.0], [1.0, 0.0, 0.0], [1.0, 0.0, 0.0]]


In [4]:
def run_generation(neat, inputs, outputs):
    evaluations = neat.evaluate_population(inputs, outputs, 100, 0.01)
    participants_id, remaining_id = neat.select_participants(evaluations)

    best = None
    best_id = participants_id[0][0]
    best_score = participants_id[0][1]
    best_losses = participants_id[0][2]

    for p in neat.population:
        if p.id == best_id:
            best = [p, best_score, best_losses]
            break

    print("Best of generation: ", best_id, best_score)
    plot_dag(best[0])

    neat.population = neat.evolve(participants_id, remaining_id)
    """ for dag in neat.population:
        print('-'*150)
        print("id", dag.id)
        plot_dag(dag)
        print(dag) """

In [5]:
#run_generation(neat, inputs, outputs)

In [6]:
neat = NEAT(len(inputs[0]), len(outputs[0]), population_size=4, with_fully_connect=True, error_function=MSE(), output_activation=Sigmoid())

In [7]:
best_of_generations = neat.run(inputs, outputs, epochs=100, generations=20)

100%|██████████| 4/4 [00:00<00:00, 4021.38it/s]


------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 1/20


evaluating DAG's: 100%|██████████| 4/4 [00:00<00:00,  5.82it/s]


Best of generation:  1 Best Score: 0.029561570126467828
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 2/20


evaluating DAG's: 100%|██████████| 4/4 [00:00<00:00,  5.68it/s]


Best of generation:  0-1 Best Score: 0.7494110672780977
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 3/20


evaluating DAG's: 100%|██████████| 4/4 [00:00<00:00,  5.47it/s]


Best of generation:  0-1 Best Score: 0.7494398244879128
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 4/20


evaluating DAG's: 100%|██████████| 4/4 [00:00<00:00,  5.27it/s]


Best of generation:  1-0-1 Best Score: 0.7036387244135653
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 5/20


evaluating DAG's: 100%|██████████| 4/4 [00:00<00:00,  4.86it/s]


Best of generation:  1-0-2-1 Best Score: 0.013958247725180693
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 6/20


evaluating DAG's: 100%|██████████| 4/4 [00:00<00:00,  4.83it/s]


Best of generation:  1-0-2-1 Best Score: 0.013819285256905513
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 7/20


evaluating DAG's: 100%|██████████| 4/4 [00:00<00:00,  4.74it/s]


Best of generation:  1-0-2-1 Best Score: 0.013819285256905513
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 8/20


evaluating DAG's: 100%|██████████| 4/4 [00:00<00:00,  4.45it/s]


Best of generation:  1-0-2-1 Best Score: 0.013819285256905513
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 9/20


evaluating DAG's: 100%|██████████| 4/4 [00:00<00:00,  4.34it/s]


Best of generation:  1-0-2-1 Best Score: 0.013819285256905513
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 10/20


evaluating DAG's: 100%|██████████| 4/4 [00:00<00:00,  4.37it/s]


Best of generation:  1-0-2-1 Best Score: 0.013819285256905513
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 11/20


evaluating DAG's: 100%|██████████| 4/4 [00:00<00:00,  4.12it/s]


Best of generation:  1-0-2-1 Best Score: 0.013819285256905513
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 12/20


evaluating DAG's: 100%|██████████| 4/4 [00:01<00:00,  3.99it/s]


Best of generation:  1-0-2-1 Best Score: 0.013819285256905513
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 13/20


evaluating DAG's: 100%|██████████| 4/4 [00:01<00:00,  3.99it/s]


Best of generation:  1-0-2-1 Best Score: 0.013819285256905513
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 14/20


evaluating DAG's: 100%|██████████| 4/4 [00:01<00:00,  3.71it/s]


Best of generation:  1-0-2-1 Best Score: 0.013819285256905513
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 15/20


evaluating DAG's: 100%|██████████| 4/4 [00:01<00:00,  3.64it/s]


Best of generation:  1-0-2-1 Best Score: 0.013819285256905513
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 16/20


evaluating DAG's: 100%|██████████| 4/4 [00:01<00:00,  3.07it/s]


Best of generation:  1-0-2-1 Best Score: 0.013819285256905513
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 17/20


evaluating DAG's: 100%|██████████| 4/4 [00:01<00:00,  3.53it/s]


Best of generation:  1-0-2-1 Best Score: 0.013819285256905513
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 18/20


evaluating DAG's: 100%|██████████| 4/4 [00:01<00:00,  3.33it/s]


Best of generation:  1-0-2-1 Best Score: 0.013819285256905513
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 19/20


evaluating DAG's: 100%|██████████| 4/4 [00:01<00:00,  3.22it/s]


Best of generation:  1-0-2-1 Best Score: 0.013819285256905513
------------------------------------------------------------------------------------------------------------------------------------------------------
Generation 20/20


evaluating DAG's: 100%|██████████| 4/4 [00:01<00:00,  3.06it/s]

Best of generation:  1-0-2-1 Best Score: 0.013819285256905513


In [8]:
""" for dag in neat.population:
    print('-'*150)
    print("id", dag.id)
    plot_dag(dag)
    print(dag) """

' for dag in neat.population:\n    print(\'-\'*150)\n    print("id", dag.id)\n    plot_dag(dag)\n    print(dag) '

In [9]:
target_dag : DAG = best_of_generations[-1][0]

plot_dag(target_dag)

print('Has circles:', target_dag.check_for_circular())

Has circles: True


In [10]:
correct = 0
for i in np.random.randint(0, len(inputs), 20):
    res = target_dag.process([inputs[i]])
    print(f"Output: {np.argmax(res)} | Expected: {np.argmax(outputs[i])}")
    if np.argmax(res) == np.argmax(outputs[i]):
        correct += 1
print(f"Accuracy: {correct / 20 * 100}%")

Output: 2 | Expected: 2
Output: 2 | Expected: 2
Output: 2 | Expected: 1
Output: 0 | Expected: 0
Output: 0 | Expected: 0
Output: 2 | Expected: 1
Output: 2 | Expected: 1
Output: 0 | Expected: 0
Output: 2 | Expected: 2
Output: 2 | Expected: 1
Output: 0 | Expected: 0
Output: 2 | Expected: 2
Output: 2 | Expected: 2
Output: 0 | Expected: 0
Output: 0 | Expected: 0
Output: 2 | Expected: 1
Output: 2 | Expected: 2
Output: 0 | Expected: 0
Output: 2 | Expected: 2
Output: 0 | Expected: 0
Accuracy: 75.0%
